/* BioDynaMit v11.7 — additive activity, search, quality and enrichment workflows. */
(function(){
 'use strict';
 const VERSION='11.7.0',SEC='secondary_antibody';
 const ns=window.BioDynaMitV117=window.BioDynaMitV117||{};
 const v112=window.BioDynaMitV112||{},v113=window.BioDynaMitV113||{},team=window.BioDynaMitTeamV115||{};
 const S={activity:[],dedup:new Map(),observer:null,activityReady:false,paletteIndex:0,lastUndo:null};
 const SCHEMA=[{id:'Date',type:'DateTime'},{id:'ActorEmail',type:'Text'},{id:'ActorName',type:'Text'},{id:'Role',type:'Text'},{id:'EventType',type:'Text'},{id:'InventoryType',type:'Text'},{id:'ItemCode',type:'Text'},{id:'ItemName',type:'Text'},{id:'EntityType',type:'Text'},{id:'EntityCode',type:'Text'},{id:'Route',type:'Text'},{id:'Action',type:'Text'},{id:'Details',type:'Text'},{id:'SessionId',type:'Text'},{id:'SearchQuery',type:'Text'},{id:'RelatedCodes',type:'Text'}];
 const LABELS={VIEW_PRIMARY:'Consultation primaire',VIEW_SECONDARY:'Consultation secondaire',VIEW_VIAL:'Consultation vial',VIEW_STORAGE:'Consultation stockage',VIEW_ARTICLE:'Publication ouverte',VIEW_DOCUMENT:'Document ouvert',SEARCH:'Recherche avancée',RUN_PANEL:'Panel IF exécuté',START_INVENTORY:'Inventaire lancé'};
 ns.version=VERSION;ns.schema=SCHEMA;ns.eventLabels=LABELS;
 const e=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const norm=v=>String(v??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
 const tr=n=>{try{return rows(state.data[n]||v112.data?.[n]||v113.data?.[n])||[]}catch(_){return[]}};
 const nativeApply=actions=>{const fn=v113._nativeApply||window.grist?.docApi?.applyUserActions?.bind(window.grist.docApi);if(!fn)throw Error('Connexion Grist requise.');return fn(actions)};
 function session(){return v113.sessionId||('S-'+Date.now().toString(36));}
 function role(){return v113.role||'unconfigured'}
 async function tables(){try{return await grist.docApi.listTables()}catch(_){return[]}}
 async function fetchActivity(){if(!(await tables()).includes('TeamActivityLog')){S.activityReady=false;S.activity=[];return[]}try{const raw=await grist.docApi.fetchTable('TeamActivityLog');S.activity=rows(raw);S.activityReady=true;return S.activity}catch(_){S.activityReady=false;return[]}}
 async function ensureSchema(){
  if(role()!=='admin'&&role()!=='unconfigured')throw Error('Action réservée aux administrateurs.');
  if((await tables()).includes('TeamActivityLog'))return false;
  await nativeApply([['AddTable','TeamActivityLog',SCHEMA]]);await fetchActivity();return true;
 }
 async function track(type,ctx={},dedupMs=60000){
  if(!state?.connected||!S.activityReady||!LABELS[type])return false;
  const key=[type,ctx.entityCode||ctx.itemCode||'',ctx.route||state.route,ctx.searchQuery||''].join('|'),now=Date.now();
  if(now-(S.dedup.get(key)||0)<dedupMs)return false;
  try{await nativeApply([['AddRecord','TeamActivityLog',null,{Date:now/1000,EventType:type,InventoryType:ctx.inventoryType||'',ItemCode:ctx.itemCode||'',ItemName:ctx.itemName||'',EntityType:ctx.entityType||'',EntityCode:ctx.entityCode||'',Route:ctx.route||state.route||'',Action:LABELS[type],Details:String(ctx.details||'').slice(0,1800),SessionId:session(),SearchQuery:ctx.searchQuery||'',RelatedCodes:ctx.relatedCodes||''}]]);S.dedup.set(key,now);return true}catch(err){console.warn('v11.7 activity:',err);return false}
 }
 function primaryContext(){const a=tr('Antibodies').find(x=>Number(x.id)===Number(state.selectedAntibody));return a?{inventoryType:'primary_antibody',itemCode:a.Code||'',itemName:a.Name||a.FullName||'',entityType:'Antibody',entityCode:a.Code||String(a.id)}:null}
 function secondaryContext(){try{const id=v112.inventorySelected?.[SEC],d=v112.inventoryData?.(SEC),i=d?.items?.find(x=>String(x.id)===String(id));return i?{inventoryType:SEC,itemCode:i.code||'',itemName:i.name||'',entityType:'InventoryItem',entityCode:i.code||String(i.id)}:null}catch(_){return null}}
 function contextualTrack(){
  if(state.route==='antibody-detail'){const c=primaryContext();if(c)track('VIEW_PRIMARY',c)}
  if(state.route===`inv:${SEC}`&&v112.inventoryView?.[SEC]==='detail'){const c=secondaryContext();if(c)track('VIEW_SECONDARY',c)}
  if(state.route==='box3d'||document.querySelector('.storage-integrated-v11')){const b=tr('Boxes').find(x=>Number(x.id)===Number(state.selectedBox));track('VIEW_STORAGE',{entityType:'Box',entityCode:b?.Code||'',itemName:b?.Name||'',details:[b?.Temperature,b?.Rack].filter(Boolean).join(' · ')});const v=tr('Vials').find(x=>Number(x.id)===Number(state.selectedVial));if(v)track('VIEW_VIAL',{inventoryType:'primary_antibody',itemCode:v.Code||'',itemName:v.Code||'',entityType:'Vial',entityCode:v.Code||String(v.id)})}
 }
 function meaningfulClick(ev){
  const t=ev.target.closest('button,a');if(!t)return;
  if(t.id==='v115AnalyzePanel'){const codes=(team.panelSelections||[]).filter(Boolean);track('RUN_PANEL',{entityType:'PanelIF',entityCode:codes.join('+'),relatedCodes:codes.join('|'),details:`Panel IF : ${codes.join(' + ')}`},0)}
  if(t.id==='v115InvStart'){const sel=document.querySelector('#v115InvContainer');track('START_INVENTORY',{entityType:'InventorySession',entityCode:sel?.value||'',details:sel?.selectedOptions?.[0]?.textContent||''},0)}
  if(t.matches('[data-v115-search],#v115SearchBtn,#v115SearchGo')){const q=document.querySelector('#v115Search')?.value||team.searchQuery||'';if(q.trim())track('SEARCH',{entityType:'Search',searchQuery:q,details:`Recherche avancée : ${q}`},5000)}
  if(t.matches('[data-openbox],[data-sv11-vial],#vialPanel button')){const p=tr('Positions').find(x=>Number(x.Vial)===Number(state.selectedVial));const v=tr('Vials').find(x=>Number(x.id)===Number(state.selectedVial));if(v)track('VIEW_VIAL',{inventoryType:'primary_antibody',itemCode:v.Code||'',itemName:v.Code||'',entityType:'Vial',entityCode:v.Code||String(v.id),details:p?.Slot||''})}
  if(t.tagName==='A'&&t.href){if(/pubmed\.ncbi\.nlm\.nih\.gov|doi\.org/.test(t.href)){const pm=(t.href.match(/pubmed[^/]*\/([^/]+)/)||[])[1]||'';track('VIEW_ARTICLE',{entityType:'Publication',entityCode:pm,details:t.closest('article')?.querySelector('h3')?.textContent||t.href})}else if(t.closest('[data-document],.v112-documents,.documents'))track('VIEW_DOCUMENT',{entityType:'Document',entityCode:t.href,details:t.textContent})}
 }

 /* Generic searchable select. Underlying select remains the source of value. */
 function mountCombo(select,options={}){
  if(!select||select.dataset.v117Combo)return;select.dataset.v117Combo='1';select.hidden=true;
  const wrap=document.createElement('div');wrap.className='v117-combo';const input=document.createElement('input');input.className='v117-combo-input';input.type='text';input.placeholder=options.placeholder||'Rechercher…';input.setAttribute('role','combobox');input.setAttribute('aria-expanded','false');
  const clear=document.createElement('button');clear.type='button';clear.className='v117-combo-clear';clear.textContent='×';clear.setAttribute('aria-label','Effacer la sélection');const menu=document.createElement('div');menu.className='v117-combo-menu';menu.hidden=true;menu.setAttribute('role','listbox');wrap.append(input,clear,menu);select.after(wrap);let active=0;
  const values=()=>[...select.options].filter(o=>o.value).map(o=>({value:o.value,label:o.textContent,search:[o.textContent,o.dataset.search||''].join(' '),option:o}));
  const set=value=>{select.value=value;const o=select.selectedOptions[0];input.value=o&&o.value?o.textContent:'';select.dispatchEvent(new Event('change',{bubbles:true}));close()};
  const close=()=>{menu.hidden=true;input.setAttribute('aria-expanded','false')};
  const draw=()=>{const q=norm(input.value),all=values();let list=all.filter(x=>!q||norm(x.search).includes(q));list=list.slice(0,20);active=Math.min(active,Math.max(0,list.length-1));menu.innerHTML=list.length?list.map((x,i)=>`<button type="button" class="v117-combo-option" role="option" data-value="${e(x.value)}" aria-selected="${i===active}"><b>${e(x.label.split(' · ')[0])}</b><small>${e(x.label.split(' · ').slice(1).join(' · '))}</small></button>`).join(''):'<div class="v117-combo-empty">Aucun résultat.</div>';menu.hidden=false;input.setAttribute('aria-expanded','true');menu.querySelectorAll('[data-value]').forEach(b=>b.onmousedown=ev=>{ev.preventDefault();set(b.dataset.value)})};
  input.addEventListener('focus',()=>{if(!input.value)draw()});input.addEventListener('input',()=>{active=0;draw()});input.addEventListener('keydown',ev=>{const items=[...menu.querySelectorAll('[data-value]')];if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();active=(active+(ev.key==='ArrowDown'?1:-1)+Math.max(1,items.length))%Math.max(1,items.length);items.forEach((x,i)=>x.setAttribute('aria-selected',i===active));items[active]?.scrollIntoView({block:'nearest'})}if(ev.key==='Enter'&&items[active]){ev.preventDefault();set(items[active].dataset.value)}if(ev.key==='Escape')close()});
  clear.onclick=()=>{input.value='';set('');input.focus()};document.addEventListener('click',ev=>{if(!wrap.contains(ev.target))close()},{capture:true});const current=select.selectedOptions[0];if(current?.value)input.value=current.textContent;
 }
 function enhancePanel(){document.querySelectorAll('[data-v115-primary]').forEach(sel=>{[...sel.options].forEach(o=>{const item=team.allItems?.().find(i=>String(i.code)===String(o.value));if(item)o.dataset.search=[item.name,item.target,item.code,item.supplier,item.catalogNumber,item.hostSpecies,item.fluorophore].join(' ')});mountCombo(sel,{placeholder:'Rechercher un anticorps…'})})}

 /* Global command/search palette. */
 function searchEntries(){
  const out=[{kind:'Action',icon:'⚗',title:'Construire un Panel IF',meta:'Outils équipe',search:'panel if immunofluorescence',open:()=>{team.tab='panel';go('team-tools')}}];
  tr('Antibodies').forEach(a=>out.push({kind:'Primaire',icon:'Y',title:a.Name||a.FullName||a.Code,meta:[a.CatalogNumber,a.Supplier,a.HostSpecies].filter(Boolean).join(' · '),search:[a.Name,a.FullName,a.Code,a.CatalogNumber,a.Supplier,a.HostSpecies,a.Target].join(' '),open:()=>{state.selectedAntibody=Number(a.id);go('antibody-detail')}}));
  try{const d=v112.inventoryData?.(SEC);(d?.items||[]).forEach(i=>out.push({kind:'Secondaire',icon:'S',title:i.name||i.code,meta:[i.catalogNumber,i.supplier,i.fluorophore].filter(Boolean).join(' · '),search:[i.name,i.code,i.catalogNumber,i.supplier,i.hostSpecies,i.targetSpecies,i.fluorophore].join(' '),open:()=>{v112.inventorySelected[SEC]=i.id;v112.inventoryView[SEC]='detail';go(`inv:${SEC}`)}}));}catch(_){ }
  tr('Vials').forEach(v=>out.push({kind:'Vial',icon:'▥',title:v.Code||`V-${v.id}`,meta:'Exemplaire physique',search:[v.Code,v.Status,v.FillStatus].join(' '),open:()=>{const p=tr('Positions').find(x=>Number(x.Vial)===Number(v.id));if(p){state.selectedVial=Number(v.id);state.selectedBox=Number(p.Box);go('box3d')}else{go('vials')}}}));
  tr('Boxes').forEach(b=>out.push({kind:'Boîte',icon:'❄',title:b.Name||b.Code,meta:[b.Temperature,b.Rack].filter(Boolean).join(' · '),search:[b.Name,b.Code,b.Temperature,b.Rack].join(' '),open:()=>{state.selectedBox=Number(b.id);go('box3d')}}));
  tr('Documents').forEach(d=>out.push({kind:'Document',icon:'▣',title:d.Title||d.Link||'Document',meta:d.Type||'',search:[d.Title,d.Type,d.Notes,d.Link].join(' '),open:()=>d.Link?window.open(d.Link,'_blank','noopener'):go('documents')}));return out;
 }
 function score(entry,q){const n=norm(q),tokens=n.split(' ').filter(Boolean),hay=norm(entry.search+' '+entry.title+' '+entry.meta);if(!n)return 1;if(norm(entry.title)===n)return 100;if(hay.split(' ').includes(n))return 70;return tokens.every(t=>hay.includes(t))?40+tokens.length:0}
 function openPalette(){if(document.querySelector('.v117-palette-backdrop'))return;const box=document.createElement('div');box.className='v117-palette-backdrop';box.innerHTML='<div class="v117-palette"><input aria-label="Recherche globale" placeholder="Rechercher une référence, un vial, une boîte…"><div class="v117-palette-results"></div><div class="v117-palette-foot">↑ ↓ naviguer · Entrée ouvrir · Échap fermer · Ctrl K ouvrir</div></div>';document.body.append(box);const input=box.querySelector('input'),res=box.querySelector('.v117-palette-results');let current=[];const close=()=>box.remove();const draw=()=>{current=searchEntries().map(x=>({...x,score:score(x,input.value)})).filter(x=>x.score).sort((a,b)=>b.score-a.score).slice(0,18);S.paletteIndex=Math.min(S.paletteIndex,Math.max(0,current.length-1));res.innerHTML=current.length?current.map((x,i)=>`<button class="v117-palette-row ${i===S.paletteIndex?'active':''}" data-i="${i}"><span>${e(x.icon)}</span><span><b>${e(x.title)}</b><small>${e(x.meta)}</small></span><small>${e(x.kind)}</small></button>`).join(''):'<div class="empty">Aucun résultat.</div>';res.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{current[Number(b.dataset.i)].open();close()})};input.oninput=()=>{S.paletteIndex=0;draw()};input.onkeydown=ev=>{if(ev.key==='Escape')close();if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();S.paletteIndex=(S.paletteIndex+(ev.key==='ArrowDown'?1:-1)+Math.max(1,current.length))%Math.max(1,current.length);draw()}if(ev.key==='Enter'&&current[S.paletteIndex]){current[S.paletteIndex].open();close()}};box.onclick=ev=>{if(ev.target===box)close()};draw();input.focus()}

 /* Shared product enrichment: controlled proxy optional, official/manual fallback always. */
 const PROVIDERS={
  'thermo fisher':{name:'Thermo Fisher Scientific',domain:'thermofisher.com',search:'https://www.thermofisher.com/search/results?query={catalog}'},
  'cell signaling':{name:'Cell Signaling Technology',domain:'cellsignal.com',search:'https://www.cellsignal.com/search?Ntt={catalog}'},
  'abcam':{name:'Abcam',domain:'abcam.com',search:'https://www.abcam.com/en-us/search?keywords={catalog}'},
  'santa cruz':{name:'Santa Cruz Biotechnology',domain:'scbt.com',search:'https://www.scbt.com/search?keywords={catalog}'},
  'biolegend':{name:'BioLegend',domain:'biolegend.com',search:'https://www.biolegend.com/en-us/search-results?searchTerm={catalog}'},
  'jackson':{name:'Jackson ImmunoResearch',domain:'jacksonimmuno.com',search:'https://www.jacksonimmuno.com/catalog/products?search={catalog}'},
  'cytiva':{name:'Cytiva',domain:'cytivalifesciences.com',search:'https://www.cytivalifesciences.com/en/us/search-results?query={catalog}'},
  'millipore':{name:'MilliporeSigma',domain:'sigmaaldrich.com',search:'https://www.sigmaaldrich.com/FR/fr/search/{catalog}?focus=products&page=1&perpage=30&term={catalog}&type=product'}
 };
 function providerFor(name){const n=norm(name).replaceAll(' ',''),aliases={'thermofisher':'thermo fisher','invitrogen':'thermo fisher','cellsignalingtechnology':'cell signaling','cellsignaling':'cell signaling','santacruzbiotechnology':'santa cruz','santacruz':'santa cruz','jacksonimmunoresearch':'jackson','milliporesigma':'millipore','sigmaaldrich':'millipore'};const key=aliases[n]||Object.keys(PROVIDERS).find(k=>n.includes(k.replaceAll(' ','')));return key?PROVIDERS[key]:null}
 function officialUrl(supplier,catalog){const cfg=tr('SupplierConfig').find(x=>norm(x.Name)===norm(supplier)||norm(x.CanonicalName)===norm(supplier)||String(x.Aliases||'').split('|').some(a=>norm(a)===norm(supplier)));const template=cfg?.SearchTemplate||providerFor(supplier)?.search;return template?template.replaceAll('{catalog}',encodeURIComponent(catalog)).replaceAll('{query}',encodeURIComponent(catalog)):''}
 function itemCurrent(kind,id){if(kind==='primary')return tr('Antibodies').find(x=>Number(x.id)===Number(id));try{return v112.inventoryData?.(SEC)?.items?.find(x=>String(x.id)===String(id))?.raw}catch(_){return null}}
 function fieldsFor(kind){return kind==='primary'?[['Name','Nom'],['Supplier','Fournisseur'],['CatalogNumber','Référence'],['Target','Cible'],['HostSpecies','Host'],['ApplicationsText','Applications'],['Comments','Commentaires'],['Website','URL produit']]:[['Name','Nom'],['Supplier','Fournisseur'],['CatalogNumber','Référence'],['Target','Cible'],['TargetSpecies','Espèce cible'],['HostSpecies','Host'],['Fluorophore','Fluorophore'],['Comments','Commentaires'],['Website','URL produit']]}
 function quickEdit(kind,id){const r=itemCurrent(kind,id);if(!r)return;modal(`<h2>Modification rapide</h2><p class="subtitle">Corrige seulement ce qui a changé. Les autres valeurs seront conservées.</p>${fieldsFor(kind).map(([k,l])=>`<div class="v117-field-row"><label for="v117q${k}">${e(l)}</label><input id="v117q${k}" data-field="${k}" value="${e(r[k]||'')}"><span></span></div>`).join('')}<div class="row" style="justify-content:flex-end;margin-top:16px"><button class="btn" id="v117Cancel">Annuler</button><button class="btn btn-primary" id="v117Save">Enregistrer</button></div>`);document.querySelector('#v117Cancel').onclick=closeModal;document.querySelector('#v117Save').onclick=async()=>{const updates={};document.querySelectorAll('#modalCard [data-field]').forEach(x=>{if(String(r[x.dataset.field]||'')!==x.value)updates[x.dataset.field]=x.value});if(!Object.keys(updates).length)return closeModal();const table=kind==='primary'?'Antibodies':'InventoryItems';try{await grist.docApi.applyUserActions([['UpdateRecord',table,Number(r.id),updates]]);closeModal();toast('✓ Anticorps mis à jour');await loadAll();render()}catch(err){toast(`Modification impossible : ${err.message||err}`)}}}
 function enrichment(kind,id){const r=itemCurrent(kind,id);if(!r)return;const supplier=r.Supplier||'',catalog=r.CatalogNumber||'',url=officialUrl(supplier,catalog);modal(`<h2>Vérifier par référence</h2><p class="subtitle">Aucune donnée existante ne sera remplacée sans validation humaine.</p><div class="form-grid"><div class="field"><label>Fournisseur</label><input id="v117Supplier" value="${e(supplier)}"></div><div class="field"><label>Référence catalogue</label><input id="v117Catalog" value="${e(catalog)}"></div></div><div class="v117-source"><b>Source prioritaire :</b> site officiel du fournisseur. La v11.7 n’utilise ni proxy CORS public ni contournement anti-bot.</div><div id="v117LookupResult">${url?`<a class="btn" href="${e(url)}" target="_blank" rel="noopener noreferrer">Ouvrir la recherche officielle ↗</a>`:'<div class="banner">Aucune méthode automatique sûre configurée. Complète SupplierConfig ou poursuis manuellement.</div>'}</div><div class="row" style="justify-content:flex-end;margin-top:16px"><button class="btn" id="v117LookupClose">Fermer</button><button class="btn btn-primary" id="v117LookupManual">Comparer une proposition</button></div>`);document.querySelector('#v117LookupClose').onclick=closeModal;document.querySelector('#v117LookupManual').onclick=()=>proposal(kind,id,{Supplier:document.querySelector('#v117Supplier').value.trim(),CatalogNumber:document.querySelector('#v117Catalog').value.trim(),Website:officialUrl(document.querySelector('#v117Supplier').value,document.querySelector('#v117Catalog').value)})}
 function proposal(kind,id,seed){const r=itemCurrent(kind,id),fields=fieldsFor(kind);modal(`<h2>Prévisualisation avant import</h2><p class="subtitle">Renseigne uniquement les valeurs vérifiées sur la source officielle, puis choisis les champs à importer.</p>${fields.map(([k,l])=>`<div class="v117-checkline"><input type="checkbox" data-check="${k}" ${seed[k]?'checked':''}><b>${e(l)}</b><input data-proposed="${k}" value="${e(seed[k]||r[k]||'')}"></div>`).join('')}<div class="v117-source">Valeur BioDynaMit actuelle conservée pour chaque champ non coché.</div><div class="row" style="justify-content:flex-end;margin-top:16px"><button class="btn" id="v117ProposalBack">Retour</button><button class="btn btn-primary" id="v117ProposalSave">Valider les champs cochés</button></div>`);document.querySelector('#v117ProposalBack').onclick=()=>enrichment(kind,id);document.querySelector('#v117ProposalSave').onclick=async()=>{const up={};document.querySelectorAll('[data-check]:checked').forEach(c=>up[c.dataset.check]=document.querySelector(`[data-proposed="${c.dataset.check}"]`).value);if(!Object.keys(up).length)return toast('Choisis au moins un champ.');try{await grist.docApi.applyUserActions([['UpdateRecord',kind==='primary'?'Antibodies':'InventoryItems',Number(r.id),up]]);closeModal();toast('✓ Référence vérifiée et mise à jour');await loadAll();render()}catch(err){toast(`Enregistrement impossible : ${err.message||err}`)}}}
 function injectDetailActions(){if(document.querySelector('.v117-context'))return;let kind,id;if(state.route==='antibody-detail'){kind='primary';id=state.selectedAntibody}else if(state.route===`inv:${SEC}`&&v112.inventoryView?.[SEC]==='detail'){kind='secondary';id=v112.inventorySelected?.[SEC]}else return;const anchor=document.querySelector('#content .tabs')||document.querySelector('#content .page-title');if(!anchor)return;const bar=document.createElement('div');bar.className='v117-context';bar.innerHTML='<button class="btn v117-main" data-v117-use>Utiliser</button><button class="btn" data-v117-review>Ajouter un retour</button><button class="btn" data-v117-edit>Modification rapide</button><button class="btn" data-v117-verify>Vérifier par référence</button><button class="btn" data-v117-order>Commander</button>';anchor.after(bar);bar.querySelector('[data-v117-edit]').onclick=()=>quickEdit(kind,id);bar.querySelector('[data-v117-verify]').onclick=()=>enrichment(kind,id);bar.querySelector('[data-v117-use]').onclick=()=>{team.tab='usage';go('team-tools')};bar.querySelector('[data-v117-review]').onclick=()=>{team.tab='reviews';go('team-tools')};bar.querySelector('[data-v117-order]').onclick=()=>{team.tab='orders';go('team-tools')}}

 /* Grouped reconciliation keeps InventoryPositions untouched. */
 function pendingUnits(){try{return (v112.inventoryData?.(SEC)?.units||[]).filter(u=>{const m=norm(u.matchStatus),s=norm(u.status);return s==='a reconcilier'||/review|unresolved/.test(m)||(m==='other reagent'&&s!=='en stock')})}catch(_){return[]}}
 function groupPending(){const d=v112.inventoryData?.(SEC);const ps=d?.positions||[],cs=d?.containers||[];const map=new Map();pendingUnits().forEach(u=>{const key=norm(u.rawLabel||u.detectedTargetSpecies||u.code);if(!map.has(key))map.set(key,{label:u.rawLabel||u.code,units:[],positions:[]});const g=map.get(key);g.units.push(u);const p=ps.find(x=>String(x.unitCode)===String(u.code));const c=p&&cs.find(x=>String(x.code)===String(p.containerCode));if(p)g.positions.push(`${c?.name||p.containerCode||''} / ${p.slot}`)});return [...map.values()].sort((a,b)=>b.units.length-a.units.length)}
 function groupedReconcile(index=0){const groups=groupPending();if(!groups.length)return toast('Aucun vial non relié.');index=Math.max(0,Math.min(index,groups.length-1));const g=groups[index],items=v112.inventoryData?.(SEC)?.items||[];modal(`<div><p class="u127-eyebrow">GRAND NETTOYAGE DES SECONDAIRES</p><h2>${e(g.label)}</h2><div class="v117-progressline"><span>Problème ${index+1} / ${groups.length}</span><span>${groups.length-index-1} restant(s)</span></div><div class="v117-group"><b>${g.units.length} vial(s) concernés</b><div class="v117-position-list">${g.positions.map(x=>`<span>${e(x)}</span>`).join('')}</div></div><div class="field"><label>Relier à une référence existante</label><select id="v117GroupItem"><option value="">— Rechercher une référence —</option>${items.map(i=>`<option value="${e(i.id)}" data-search="${e([i.name,i.code,i.catalogNumber,i.supplier,i.hostSpecies,i.targetSpecies,i.fluorophore].join(' '))}">${e(i.name)} · ${e(i.catalogNumber||'—')} · ${e(i.supplier||'—')}</option>`).join('')}</select></div><div class="v117-source">Cette action modifiera uniquement la liaison des vials. Leurs positions resteront inchangées.</div><div class="row" style="justify-content:space-between;margin-top:16px"><button class="btn" id="v117GroupClose">Fermer</button><button class="btn btn-primary" id="v117GroupSave">Relier ${g.units.length} vial(s) et suivant</button></div></div>`);mountCombo(document.querySelector('#v117GroupItem'));document.querySelector('#v117GroupClose').onclick=closeModal;document.querySelector('#v117GroupSave').onclick=async()=>{const item=items.find(i=>String(i.id)===document.querySelector('#v117GroupItem').value);if(!item)return toast('Choisis une référence.');if(!confirm(`Cette action va relier ${g.units.length} vial(s) à ${item.catalogNumber||item.code}. Les positions seront conservées.`))return;const before=g.units.map(u=>({id:u.id,item:u.itemId||u.raw?.Item||0,status:u.status,match:u.matchStatus,candidate:u.candidateItemCode}));const actions=g.units.map(u=>['UpdateRecord','InventoryUnits',Number(u.id),{Item:Number(item.id),Status:'En stock',MatchStatus:'validated',CandidateItemCode:item.code}]);if((await tables()).includes('InventoryHistory'))actions.push(['AddRecord','InventoryHistory',null,{Date:Date.now()/1000,InventoryType:SEC,Action:'Réconciliation groupée',EntityType:'InventoryUnitGroup',EntityCode:item.code,Details:`${g.units.length} vials reliés à ${item.code}; positions conservées`,User:'Grist'}]);try{await grist.docApi.applyUserActions(actions);S.lastUndo={before,label:g.label};toast(`✓ ${g.units.length} vials reliés à ${item.catalogNumber||item.code}`);await loadAll();groupedReconcile(Math.min(index,groupPending().length-1))}catch(err){toast(`Réconciliation impossible : ${err.message||err}`)}}}
 function injectQualityActions(){const root=document.querySelector('.u126-antibody-list');if(!root||root.querySelector('[data-v117-group]'))return;if(root.dataset.u126Kind==='secondary'){const b=document.createElement('button');b.className='btn btn-primary';b.dataset.v117Group='1';b.textContent='Traiter les non reliés par groupes';b.onclick=()=>groupedReconcile(0);root.querySelector('.u125-quality-summary .row')?.appendChild(b)}root.querySelectorAll('[data-u126-row]').forEach(row=>{const [kind,id]=row.dataset.u126Row.split(':');const cell=row.querySelector('.u126-col-qc');const current=cell?.firstElementChild;if(!cell||!current||current.matches('button'))return;const b=document.createElement('button');b.className=current.className;b.innerHTML=current.innerHTML;b.title=current.title;b.onclick=ev=>{ev.stopPropagation();kind==='primary'?enrichment('primary',id):enrichment('secondary',id)};current.replaceWith(b)})}

 function metricCard(n,label){return `<div class="v117-metric"><b>${n}</b><span>${e(label)}</span></div>`}
 function renderActivitySection(){
  if(role()!=='admin'&&role()!=='unconfigured')return;const host=document.querySelector('#content');if(!host||host.querySelector('#v117TeamActivity'))return;const sec=document.createElement('section');sec.id='v117TeamActivity';sec.className='card card-pad v117-activity v117-admin-only';host.append(sec);
  if(!S.activityReady){sec.innerHTML='<h2>Activité de l’équipe</h2><p class="subtitle">Journalise uniquement les consultations fonctionnelles significatives.</p><button class="btn btn-primary" id="v117InitActivity">Créer TeamActivityLog</button><div class="v117-transparency">Certaines consultations seront journalisées pour la traçabilité, l’amélioration de la BDD et la connaissance des ressources utilisées.</div>';sec.querySelector('#v117InitActivity').onclick=async()=>{try{await ensureSchema();toast('Table TeamActivityLog créée. Configure maintenant les Trigger Formulas et ACL indiquées dans le README.');render()}catch(err){toast(err.message||err)}};return}
  const now=Date.now()/1000,member=r=>r.ActorEmail||r.ActorName||'Identité non attribuée',within=d=>S.activity.filter(x=>Number(x.Date)>=now-d*86400),a7=new Set(within(7).map(member)).size,a30=new Set(within(30).map(member)).size,l30=within(30),refs=new Set(l30.map(x=>x.ItemCode||x.EntityCode).filter(Boolean)).size,pubs=l30.filter(x=>x.EventType==='VIEW_ARTICLE').length,panels=l30.filter(x=>x.EventType==='RUN_PANEL').length,memberStats=[...new Set(l30.map(member))].map(name=>{const mine=l30.filter(x=>member(x)===name),last=Math.max(0,...mine.map(x=>Number(x.Date)));return{name,count:mine.length,refs:new Set(mine.map(x=>x.ItemCode||x.EntityCode).filter(Boolean)).size,panels:mine.filter(x=>x.EventType==='RUN_PANEL').length,last}}).sort((a,b)=>b.count-a.count);
  sec.innerHTML=`<div class="row space-between"><div><h2>Activité de l’équipe</h2><p class="subtitle">Consultations fonctionnelles et actions significatives, distinctes des utilisations expérimentales.</p></div><button class="btn" id="v117ActivityRefresh">Actualiser</button></div><div class="v117-metrics">${metricCard(a7,'Membres actifs · 7 j')}${metricCard(a30,'Membres actifs · 30 j')}${metricCard(l30.length,'Consultations · 30 j')}${metricCard(refs,'Références différentes')}${metricCard(pubs,'Publications ouvertes')}${metricCard(panels,'Panels IF exécutés')}</div><h3>Résumé par membre · 30 jours</h3><div class="v117-member-table"><table><thead><tr><th>Membre</th><th>Consultations</th><th>Références</th><th>Panels IF</th><th>Dernière activité</th></tr></thead><tbody>${memberStats.length?memberStats.map(x=>`<tr><td>${e(x.name)}</td><td>${x.count}</td><td>${x.refs}</td><td>${x.panels}</td><td>${x.last?new Date(x.last*1000).toLocaleDateString('fr-FR'):'—'}</td></tr>`).join(''):'<tr><td colspan="5">Aucune activité récente.</td></tr>'}</tbody></table></div><div class="v117-activity-filters"><select id="v117ActUser"><option value="">Tous les utilisateurs</option>${[...new Set(S.activity.map(member))].sort().map(x=>`<option>${e(x)}</option>`).join('')}</select><select id="v117ActPeriod"><option value="1">Aujourd’hui</option><option value="7">7 jours</option><option value="30" selected>30 jours</option><option value="0">Tout</option></select><select id="v117ActType"><option value="">Tous les événements</option>${Object.entries(LABELS).map(([k,v])=>`<option value="${k}">${e(v)}</option>`).join('')}</select><input id="v117ActQuery" placeholder="Référence ou ressource"><button class="btn" id="v117ActApply">Filtrer</button></div><div id="v117ActivityList"></div><div class="v117-transparency">Transparence : certaines consultations fonctionnelles sont enregistrées pour la traçabilité, l’amélioration de la BDD et la connaissance des ressources utilisées. Les clics ordinaires, le scroll, les mouvements de souris et le temps passé ne sont pas suivis.</div>`;
  const draw=()=>{const days=Number(sec.querySelector('#v117ActPeriod').value),user=sec.querySelector('#v117ActUser').value,type=sec.querySelector('#v117ActType').value,q=norm(sec.querySelector('#v117ActQuery').value);const list=S.activity.filter(x=>(!days||Number(x.Date)>=now-days*86400)&&(!user||member(x)===user)&&(!type||x.EventType===type)&&(!q||norm([x.ItemCode,x.ItemName,x.EntityCode,x.Details].join(' ')).includes(q))).sort((a,b)=>Number(b.Date)-Number(a.Date)).slice(0,100);sec.querySelector('#v117ActivityList').innerHTML=list.length?`<div class="v117-timeline">${list.map(x=>`<div class="v117-event"><time>${new Date(Number(x.Date)*1000).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><b>${e(member(x))}</b><span>${e(LABELS[x.EventType]||x.Action||x.EventType)}${x.ItemName||x.EntityCode?` — ${e(x.ItemName||x.EntityCode)}`:''}</span><small>${e(x.Role||'')}</small></div>`).join('')}</div>`:'<div class="empty">Aucune activité pour ces filtres.</div>'};draw();sec.querySelector('#v117ActApply').onclick=draw;sec.querySelector('#v117ActivityRefresh').onclick=async()=>{await fetchActivity();sec.remove();renderActivitySection()}
 }
 function adminActivityHook(){const active=document.querySelector('[data-v113-admin="security"].active');if(active||/Sécurité\s*&\s*audit/i.test(document.querySelector('#content')?.innerText||''))renderActivitySection()}
 function decorate(){enhancePanel();injectDetailActions();injectQualityActions();adminActivityHook();contextualTrack()}
 function installObserver(){if(S.observer)return;let queued=false;S.observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})});S.observer.observe(document.getElementById('content'),{childList:true,subtree:true})}
 async function bootstrap(){document.addEventListener('click',meaningfulClick,true);document.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='k'){ev.preventDefault();openPalette()}});installObserver();let n=0;while(!state?.connected&&n++<40)await new Promise(r=>setTimeout(r,250));if(state?.connected)await fetchActivity();decorate()}
 ns.track=track;ns.ensureSchema=ensureSchema;ns.mountCombo=mountCombo;ns.openPalette=openPalette;ns.enrichment=enrichment;ns.groupedReconcile=groupedReconcile;ns.providers=PROVIDERS;ns._test={score,providerFor,officialUrl,groupPending,pendingUnits};bootstrap();
})();
