/* BioDynaMit v11.2 — Security & Production hardening
   Defense-in-depth layer for the custom Grist app.
   IMPORTANT: real authorization remains enforced by Grist Access Rules.
*/
(function(){
  'use strict';

  const VERSION = '11.2';
  const security = {
    widgetAccess: 'unknown',
    writeDenied: false,
    policyInstalled: false,
    lastDenied: '',
    allowedFetchHosts: new Set([
      location.hostname,
      'www.ebi.ac.uk',
      'europepmc.org',
      'www.europepmc.org',
      'docs.getgrist.com',
      'grist.numerique.gouv.fr'
    ])
  };

  function notify(msg){
    try{ toast(msg); }catch(_){ console.warn(msg); }
  }

  function isPermissionError(err){
    const s=String(err?.message || err || '').toLowerCase();
    return /permission|forbidden|access denied|not allowed|unauthori|403/.test(s);
  }

  function setReadOnly(reason){
    security.writeDenied = true;
    security.lastDenied = reason || 'Écriture refusée par Grist';
    refreshUi();
  }

  function blockProductionAction(name){
    return function(){
      console.warn(`[Security v${VERSION}] blocked: ${name}`);
      notify('Action d’administration désactivée en mode production.');
      return false;
    };
  }

  // ---------------------------------------------------------------------------
  // 1) Remove legacy administration / migration surfaces from production UI
  // ---------------------------------------------------------------------------
  function cleanProductionUi(){
    document.querySelectorAll('[data-route="admin"]').forEach(el=>el.remove());
    document.querySelectorAll('#addBox').forEach(el=>el.remove());

    if(!document.getElementById('bdmSecurityBadge')){
      const host=document.querySelector('.sidebar-bottom');
      if(host){
        const badge=document.createElement('div');
        badge.id='bdmSecurityBadge';
        badge.style.cssText='font-size:11px;color:#dcecff;padding:8px 10px;border:1px solid rgba(255,255,255,.16);border-radius:8px;line-height:1.35;background:rgba(255,255,255,.05)';
        badge.innerHTML='🔒 <b>Mode production</b><br><span style="opacity:.75">v11.2 · actions structurelles bloquées</span>';
        host.insertBefore(badge,host.firstChild);
      }
    }

    if(security.writeDenied){
      const selectors=[
        '#addAb','#addDoc','#addNote','#v1115AddMedia',
        '[data-sv11-add]','[data-sv11-edit]','[data-sv11-move]',
        '[data-sv11-empty]','[data-sv11-remove]',
        '[data-v1114-add]','[data-v1115-addprotocol]'
      ];
      document.querySelectorAll(selectors.join(',')).forEach(btn=>{
        if(btn.tagName==='BUTTON'){
          btn.disabled=true;
          btn.title='Lecture seule : vos droits Grist ne permettent pas cette modification.';
        }
      });
    }

    // Harden all external links/images generated by the application.
    document.querySelectorAll('a[href]').forEach(a=>{
      const href=String(a.getAttribute('href')||'').trim();
      if(/^\s*javascript:/i.test(href)){
        a.removeAttribute('href');
        a.title='Lien bloqué pour raison de sécurité';
      }
      if(a.target==='_blank'){
        a.rel='noopener noreferrer';
        a.referrerPolicy='no-referrer';
      }
    });
    document.querySelectorAll('img[src]').forEach(img=>{
      img.referrerPolicy='no-referrer';
      img.loading=img.loading || 'lazy';
    });
  }

  function refreshUi(){
    cleanProductionUi();
  }

  // Block direct access to legacy administration routes.
  try{
    const previousGo=go;
    go=function(route){
      if(route==='admin' || route==='setup'){
        notify('Administration technique désactivée dans la version production.');
        return previousGo('dashboard');
      }
      const out=previousGo(route);
      setTimeout(refreshUi,0);
      return out;
    };
  }catch(e){ console.warn('[Security] go wrapper unavailable',e); }

  // Disable legacy migration/schema/test-data functions even if called from console/UI.
  try{ window.createSchema = blockProductionAction('createSchema'); }catch(_){}
  try{ window.migrateAntibodies = blockProductionAction('migrateAntibodies'); }catch(_){}
  try{ window.seedTestData = blockProductionAction('seedTestData'); }catch(_){}
  try{ window.showAddBox = blockProductionAction('showAddBox'); }catch(_){}
  try{ window.saveBox = blockProductionAction('saveBox'); }catch(_){}
  try{
    window.admin=function(){
      notify('Administration technique désactivée dans la version production.');
      go('dashboard');
    };
  }catch(_){}

  // ---------------------------------------------------------------------------
  // 2) Application-level write allowlist (defense in depth, not an ACL substitute)
  // ---------------------------------------------------------------------------
  const WRITE_POLICY = {
    Antibodies: new Set(['AddRecord','UpdateRecord']),
    Vials:      new Set(['AddRecord','UpdateRecord']),
    Positions:  new Set(['UpdateRecord']),
    Documents:  new Set(['AddRecord','UpdateRecord']),
    Notes:      new Set(['AddRecord','UpdateRecord']),
    History:    new Set(['AddRecord'])
  };

  function validateAction(action){
    if(!Array.isArray(action) || !action.length) throw new Error('Action Grist invalide.');
    const op=String(action[0]||'');
    const table=String(action[1]||'');

    if(table.startsWith('_grist_')) throw new Error(`Accès à la table système ${table} bloqué.`);
    if(/Table|Column|View|Section|ModifyColumn|AddColumn|RemoveColumn/i.test(op)){
      throw new Error(`Action structurelle ${op} bloquée en production.`);
    }
    if(/RemoveRecord|BulkRemoveRecord/i.test(op)){
      throw new Error('Suppression permanente bloquée en production. Utiliser archivage/retrait physique.');
    }

    const allowedOps=WRITE_POLICY[table];
    if(!allowedOps || !allowedOps.has(op)){
      throw new Error(`Écriture ${op} sur ${table} non autorisée par la politique v${VERSION}.`);
    }
    return true;
  }

  function installWriteGuard(){
    if(security.policyInstalled) return;
    if(!window.grist?.docApi?.applyUserActions) return;

    const original=window.grist.docApi.applyUserActions.bind(window.grist.docApi);
    window.grist.docApi.applyUserActions=async function(actions){
      try{
        if(!Array.isArray(actions)) throw new Error('Liste d’actions Grist invalide.');
        actions.forEach(validateAction);
        const result=await original(actions);
        return result;
      }catch(err){
        console.error('[Security v11.2] write blocked/failed',err);
        if(isPermissionError(err)) setReadOnly('Permissions Grist insuffisantes');
        throw err;
      }
    };
    security.policyInstalled=true;
    console.info(`[Security v${VERSION}] write policy installed`);
  }

  // ---------------------------------------------------------------------------
  // 3) Outbound network guard
  //    Only the scientific watch endpoints + trusted Grist hosts are allowed.
  //    External requests omit credentials and referrer whenever possible.
  // ---------------------------------------------------------------------------
  const nativeFetch=window.fetch.bind(window);
  window.fetch=async function(input,init={}){
    let url;
    try{
      const raw=(typeof input==='string')?input:input?.url;
      url=new URL(raw,location.href);
    }catch(_){
      throw new Error('Requête externe bloquée : URL invalide.');
    }

    const sameOrigin=url.origin===location.origin;
    const allowed=sameOrigin || security.allowedFetchHosts.has(url.hostname);
    if(!allowed){
      console.warn('[Security v11.2] outbound request blocked:',url.href);
      throw new Error(`Connexion externe bloquée vers ${url.hostname}.`);
    }

    const next={...init};
    if(!sameOrigin){
      next.credentials='omit';
      next.referrerPolicy='no-referrer';
      const h=new Headers(init.headers||{});
      // Do not allow accidental authorization/cookie forwarding to scientific APIs.
      h.delete('Authorization');
      h.delete('Cookie');
      next.headers=h;
    }
    return nativeFetch(input,next);
  };

  // ---------------------------------------------------------------------------
  // 4) Observe widget access level (widget access != user role)
  // ---------------------------------------------------------------------------
  try{
    if(window.grist?.onOptions){
      grist.onOptions(function(_options,interaction){
        security.widgetAccess=interaction?.access_level || 'unknown';
        refreshUi();
      });
    }
  }catch(e){ console.warn('[Security] onOptions unavailable',e); }

  // ---------------------------------------------------------------------------
  // 5) Mutation observer keeps security attributes/hidden admin state persistent
  // ---------------------------------------------------------------------------
  const observer=new MutationObserver(()=>{
    installWriteGuard();
    cleanProductionUi();
  });
  observer.observe(document.documentElement,{subtree:true,childList:true});

  installWriteGuard();
  cleanProductionUi();

  window.BioDynaMitSecurityV112={
    version:VERSION,
    state:security,
    refresh:refreshUi,
    writePolicy:WRITE_POLICY
  };
})();
